version: '3.3'
services:
  api-service:
    external_links:
      - models-service:models-service
    container_name: api_service
    build:
      context: pseudonym_api_service
      dockerfile: Dockerfile
    env_file:
      - pseudonym_api_service/.env.list
    ports:
      - '8080:8080'

  models-service:
    container_name: models_service
    build:
      context: pseudonym_models_service
      dockerfile: Dockerfile
    env_file:
      - pseudonym_models_service/.env.list
    ports:
      - '8081:8081'

  postgres-service:
    image: postgres:latest
    container_name: postgres_service
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      - POSTGRES_USER=${PSEUDONYM_USER}
      - POSTGRES_PASSWORD=${PSEUDONYM_PASSWORD}
      - POSTGRES_DATABASE=${PSEUDONYM_DATABASE}
    ports:
      - '5432:5432'
